name: user_repository
description: User repository.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  data_providers:
    path: ../data_providers
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0
