name: quizapp
description: QuizApp Built with Flutter & Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  data_providers:
    path: packages/data_providers
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  quizzes_repository:
    path: packages/quizzes_repository
  shared:
    path: packages/shared
  topics_repository:
    path: packages/topics_repository
  transparent_image: ^2.0.0
  ui_toolkit:
    path: packages/ui_toolkit
  user_repository:
    path: packages/user_repository

dev_dependencies:
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter_gen:
  output: packages/ui_toolkit/lib/src/gen

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/covers/
