name: quizapp
description: QuizApp Built with Flutter & Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  api_client:
    path: packages/api_client
  app_core:
    path: packages/app_core
  app_ui:
    path: packages/app_ui
  equatable: ^2.0.7
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  quizzes_repository:
    path: packages/quizzes_repository
  topics_repository:
    path: packages/topics_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter_gen:
  output: packages/app_ui/lib/src/gen

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/covers/
