name: topics_repository
description: Topics repository.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  api_client:
    path: ../api_client
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1
