name: quizzes_repository
description: Quizzes repository.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  api_client:
    path: ../api_client
  app_core:
    path: ../app_core
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  very_good_analysis: ^7.0.0
