name: ui_toolkit
description: UI toolkit.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  transparent_image: ^2.0.0

dev_dependencies:
  very_good_analysis: ^2.4.0
